<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Moq.EntityFrameworkCore" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Services\Fulfillment\Fulfillment.Domain\Fulfillment.Domain.csproj" />
    <ProjectReference Include="..\..\src\Services\Fulfillment\Fulfillment.Application\Fulfillment.Application.csproj" />
    <ProjectReference Include="..\..\src\Services\Fulfillment\Fulfillment.Infrastructure\Fulfillment.Infrastructure.csproj" />
  </ItemGroup>
</Project>
