<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Microsoft.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Audit.Application\Audit.Application.csproj" />
    <ProjectReference Include="..\Audit.Infrastructure\Audit.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\ECommerce.ServiceDefaults\ECommerce.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\ECommerce.Contracts\ECommerce.Contracts.csproj" />
  </ItemGroup>

</Project>
